"""add embedding column to issues

Revision ID: 59f50406497b
Revises: a3ae1b13cb80
Create Date: 2026-06-27 03:05:36.131689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f50406497b'
down_revision: Union[str, Sequence[str], None] = 'a3ae1b13cb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('embedding', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_issues_issue_code'), 'issues', ['issue_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_issue_code'), table_name='issues')
    op.drop_column('issues', 'embedding')
    # ### end Alembic commands ###
