"""add issue_code to issues

Revision ID: d74fbfcbbc32
Revises: c17ab4f0e406
Create Date: 2026-06-26 02:30:06.729136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74fbfcbbc32'
down_revision: Union[str, Sequence[str], None] = 'c17ab4f0e406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('issues', sa.Column('issue_code', sa.String(length=50), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('issues', 'issue_code')

    # ### end Alembic commands ###
